"""empty message

Revision ID: ca89af2c7566
Revises: 8e63a1f88f1b
Create Date: 2020-04-08 01:54:47.950159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca89af2c7566'
down_revision = '8e63a1f88f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'end_time')
    # ### end Alembic commands ###
