"""empty message

Revision ID: dde2ef5b6f05
Revises: ca89af2c7566
Create Date: 2020-04-08 02:00:23.839348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde2ef5b6f05'
down_revision = 'ca89af2c7566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'end_time')
    # ### end Alembic commands ###
